server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tnutblog?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: tnutblog
    password: ?heis605312

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 782939797185-168ggearajsggj0sh78ovjbn15h5v77m.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: AemKKRWxmcAp21LCYCSA
            client-secret: EYtBuPl5DS
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao:
            client-id: da2e9fd472ecd76b4501586a6381a572
            client-secret: lQoISzQ3ID5eOxxJfHRznQLxeIUSCJU6
            scope:
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 리턴 해줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
